# Copyright 2026 EOAP
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen:
#   filename:  schema.yaml
#   timestamp: 2026-07-26T13:18:17+00:00

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel


class ErrorDetail(BaseModel):
    """
    An object to provide explicit details on a problem towards an API consumer.
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    detail: Annotated[str, Field(max_length=4096)]
    """
    A granular description on the specific error related to a body property, query parameter, path parameters, and/or header.
    """
    pointer: Annotated[str | None, Field(max_length=1024)] = None
    """
    A JSON Pointer to a specific request body property that is the source of error.
    """
    parameter: Annotated[str | None, Field(max_length=1024)] = None
    """
    The name of the query or path parameter that is the source of error.
    """
    header: Annotated[str | None, Field(max_length=1024)] = None
    """
    The name of the header that is the source of error.
    """
    code: Annotated[str | None, Field(max_length=50)] = None
    """
    A string containing additional provider specific codes to identify the error context.
    """


class ProblemDetails(BaseModel):
    """
    The `ProblemDetails` object provides detailed information about an errors that occurred during an API call execution. This problem object conforms to the [RFC9457](https://www.rfc-editor.org/info/rfc9457) (formerly [RFC7807](https://tools.ietf.org/html/rfc7807)).
    The object is extended with the following properties: - `code` - a string identifier to aid the provider team better understand the error - `errors` - and array of errors providing contextual information on the root cause of the problem
    The `ProblemDetails` referenced by this domain utilize the [EOAP Problems Registry](https://eoap.github.io/problems-registry/).
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    instance: Annotated[str | None, Field(max_length=1024)] = None
    """
    A URI reference that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced.
    """
    code: Annotated[str | None, Field(max_length=50)] = None
    """
    An API specific error code aiding the provider team understand the error based on their own potential taxonomy or registry.
    """
    errors: Annotated[list[ErrorDetail] | None, Field(max_length=1000)] = None
    """
    An array of error details to accompany a problem details response.
    """


class AlreadyExists(ProblemDetails):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: Literal["https://eoap.github.io/problems-registry/already-exists"] = (
        "https://eoap.github.io/problems-registry/already-exists"
    )
    """
    A URI reference that identifies the problem type.
    """
    status: Literal[409] = 409
    """
    The HTTP status code generated by the origin server for this occurrence of the problem.
    """
    title: Literal["Already exists"] = "Already exists"
    """
    A short, human-readable summary of the problem type. It should not change from occurrence to occurrence of the problem, except for purposes of localization.
    """
    detail: Literal["The resource being created already exists."] = (
        "The resource being created already exists."
    )
    """
    A human-readable explanation specific to this occurrence of the problem.
    """


class BadRequest(ProblemDetails):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: Literal["https://eoap.github.io/problems-registry/bad-request"] = (
        "https://eoap.github.io/problems-registry/bad-request"
    )
    """
    A URI reference that identifies the problem type.
    """
    status: Literal[400] = 400
    """
    The HTTP status code generated by the origin server for this occurrence of the problem.
    """
    title: Literal["Bad Request"] = "Bad Request"
    """
    A short, human-readable summary of the problem type. It should not change from occurrence to occurrence of the problem, except for purposes of localization.
    """
    detail: Literal["The request is invalid or malformed."] = (
        "The request is invalid or malformed."
    )
    """
    A human-readable explanation specific to this occurrence of the problem.
    """


class BusinessRuleViolation(ProblemDetails):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: Literal[
        "https://eoap.github.io/problems-registry/business-rule-violation"
    ] = "https://eoap.github.io/problems-registry/business-rule-violation"
    """
    A URI reference that identifies the problem type.
    """
    status: Literal[422] = 422
    """
    The HTTP status code generated by the origin server for this occurrence of the problem.
    """
    title: Literal["Business Rule Violation"] = "Business Rule Violation"
    """
    A short, human-readable summary of the problem type. It should not change from occurrence to occurrence of the problem, except for purposes of localization.
    """
    detail: Literal["The request body is invalid and not meeting business rules."] = (
        "The request body is invalid and not meeting business rules."
    )
    """
    A human-readable explanation specific to this occurrence of the problem.
    """


class InvalidStateTransition(ProblemDetails):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: Literal[
        "https://eoap.github.io/problems-registry/invalid-state-transition"
    ] = "https://eoap.github.io/problems-registry/invalid-state-transition"
    """
    A URI reference that identifies the problem type.
    """
    status: Literal[422] = 422
    """
    The HTTP status code generated by the origin server for this occurrence of the problem.
    """
    title: Literal["Invalid State Transition"] = "Invalid State Transition"
    """
    A short, human-readable summary of the problem type. It should not change from occurrence to occurrence of the problem, except for purposes of localization.
    """
    detail: Literal[
        "The requested transition is not valid for the current item status."
    ] = "The requested transition is not valid for the current item status."
    """
    A human-readable explanation specific to this occurrence of the problem.
    """


class Forbidden(ProblemDetails):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: Literal["https://eoap.github.io/problems-registry/forbidden"] = (
        "https://eoap.github.io/problems-registry/forbidden"
    )
    """
    A URI reference that identifies the problem type.
    """
    status: Literal[403] = 403
    """
    The HTTP status code generated by the origin server for this occurrence of the problem.
    """
    title: Literal["Forbidden"] = "Forbidden"
    """
    A short, human-readable summary of the problem type. It should not change from occurrence to occurrence of the problem, except for purposes of localization.
    """
    detail: Literal[
        "The resource could not be returned as the requestor is not authorized."
    ] = "The resource could not be returned as the requestor is not authorized."
    """
    A human-readable explanation specific to this occurrence of the problem.
    """


class Gone(ProblemDetails):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: Literal["https://eoap.github.io/problems-registry/gone"] = (
        "https://eoap.github.io/problems-registry/gone"
    )
    """
    A URI reference that identifies the problem type.
    """
    status: Literal[410] = 410
    """
    The HTTP status code generated by the origin server for this occurrence of the problem.
    """
    title: Literal["Gone"] = "Gone"
    """
    A short, human-readable summary of the problem type. It should not change from occurrence to occurrence of the problem, except for purposes of localization.
    """
    detail: Literal[
        "The requested resource is no longer available and is unlikely to be available again."
    ] = "The requested resource is no longer available and is unlikely to be available again."
    """
    A human-readable explanation specific to this occurrence of the problem.
    """


class Conflict(ProblemDetails):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: Literal["https://eoap.github.io/problems-registry/conflict"] = (
        "https://eoap.github.io/problems-registry/conflict"
    )
    """
    A URI reference that identifies the problem type.
    """
    status: Literal[409] = 409
    """
    The HTTP status code generated by the origin server for this occurrence of the problem.
    """
    title: Literal["Conflict"] = "Conflict"
    """
    A short, human-readable summary of the problem type. It should not change from occurrence to occurrence of the problem, except for purposes of localization.
    """
    detail: Literal[
        "The request conflicts with the current state of the target resource."
    ] = "The request conflicts with the current state of the target resource."
    """
    A human-readable explanation specific to this occurrence of the problem.
    """


class FailedDependency(ProblemDetails):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: Literal["https://eoap.github.io/problems-registry/failed-dependency"] = (
        "https://eoap.github.io/problems-registry/failed-dependency"
    )
    """
    A URI reference that identifies the problem type.
    """
    status: Literal[424] = 424
    """
    The HTTP status code generated by the origin server for this occurrence of the problem.
    """
    title: Literal["Failed Dependency"] = "Failed Dependency"
    """
    A short, human-readable summary of the problem type. It should not change from occurrence to occurrence of the problem, except for purposes of localization.
    """
    detail: Literal[
        "The requested action failed because an action on which it depended failed."
    ] = "The requested action failed because an action on which it depended failed."
    """
    A human-readable explanation specific to this occurrence of the problem.
    """


class InsufficientStorage(ProblemDetails):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: Literal["https://eoap.github.io/problems-registry/insufficient-storage"] = (
        "https://eoap.github.io/problems-registry/insufficient-storage"
    )
    """
    A URI reference that identifies the problem type.
    """
    status: Literal[507] = 507
    """
    The HTTP status code generated by the origin server for this occurrence of the problem.
    """
    title: Literal["Insufficient Storage"] = "Insufficient Storage"
    """
    A short, human-readable summary of the problem type. It should not change from occurrence to occurrence of the problem, except for purposes of localization.
    """
    detail: Literal[
        "The server has insufficient storage to complete the requested action."
    ] = "The server has insufficient storage to complete the requested action."
    """
    A human-readable explanation specific to this occurrence of the problem.
    """


class MethodNotAllowed(ProblemDetails):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: Literal["https://eoap.github.io/problems-registry/method-not-allowed"] = (
        "https://eoap.github.io/problems-registry/method-not-allowed"
    )
    """
    A URI reference that identifies the problem type.
    """
    status: Literal[405] = 405
    """
    The HTTP status code generated by the origin server for this occurrence of the problem.
    """
    title: Literal["Method Not Allowed"] = "Method Not Allowed"
    """
    A short, human-readable summary of the problem type. It should not change from occurrence to occurrence of the problem, except for purposes of localization.
    """
    detail: Literal["The request method is not supported by the target resource."] = (
        "The request method is not supported by the target resource."
    )
    """
    A human-readable explanation specific to this occurrence of the problem.
    """


class NotAcceptable(ProblemDetails):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: Literal["https://eoap.github.io/problems-registry/not-acceptable"] = (
        "https://eoap.github.io/problems-registry/not-acceptable"
    )
    """
    A URI reference that identifies the problem type.
    """
    status: Literal[406] = 406
    """
    The HTTP status code generated by the origin server for this occurrence of the problem.
    """
    title: Literal["Not Acceptable"] = "Not Acceptable"
    """
    A short, human-readable summary of the problem type. It should not change from occurrence to occurrence of the problem, except for purposes of localization.
    """
    detail: Literal[
        "No acceptable representation is available for the requested resource."
    ] = "No acceptable representation is available for the requested resource."
    """
    A human-readable explanation specific to this occurrence of the problem.
    """


class NotImplemented(ProblemDetails):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: Literal["https://eoap.github.io/problems-registry/not-implemented"] = (
        "https://eoap.github.io/problems-registry/not-implemented"
    )
    """
    A URI reference that identifies the problem type.
    """
    status: Literal[501] = 501
    """
    The HTTP status code generated by the origin server for this occurrence of the problem.
    """
    title: Literal["Not Implemented"] = "Not Implemented"
    """
    A short, human-readable summary of the problem type. It should not change from occurrence to occurrence of the problem, except for purposes of localization.
    """
    detail: Literal[
        "The server does not support the functionality required to fulfill the request."
    ] = "The server does not support the functionality required to fulfill the request."
    """
    A human-readable explanation specific to this occurrence of the problem.
    """


class RequestTimeout(ProblemDetails):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: Literal["https://eoap.github.io/problems-registry/request-timeout"] = (
        "https://eoap.github.io/problems-registry/request-timeout"
    )
    """
    A URI reference that identifies the problem type.
    """
    status: Literal[408] = 408
    """
    The HTTP status code generated by the origin server for this occurrence of the problem.
    """
    title: Literal["Request Timeout"] = "Request Timeout"
    """
    A short, human-readable summary of the problem type. It should not change from occurrence to occurrence of the problem, except for purposes of localization.
    """
    detail: Literal["The server timed out while waiting to receive the request."] = (
        "The server timed out while waiting to receive the request."
    )
    """
    A human-readable explanation specific to this occurrence of the problem.
    """


class UnavailableForLegalReasons(ProblemDetails):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: Literal[
        "https://eoap.github.io/problems-registry/unavailable-for-legal-reasons"
    ] = "https://eoap.github.io/problems-registry/unavailable-for-legal-reasons"
    """
    A URI reference that identifies the problem type.
    """
    status: Literal[451] = 451
    """
    The HTTP status code generated by the origin server for this occurrence of the problem.
    """
    title: Literal["Unavailable For Legal Reasons"] = "Unavailable For Legal Reasons"
    """
    A short, human-readable summary of the problem type. It should not change from occurrence to occurrence of the problem, except for purposes of localization.
    """
    detail: Literal["The requested resource is unavailable due to legal reasons."] = (
        "The requested resource is unavailable due to legal reasons."
    )
    """
    A human-readable explanation specific to this occurrence of the problem.
    """


class UnprocessableContent(ProblemDetails):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: Literal["https://eoap.github.io/problems-registry/unprocessable-content"] = (
        "https://eoap.github.io/problems-registry/unprocessable-content"
    )
    """
    A URI reference that identifies the problem type.
    """
    status: Literal[422] = 422
    """
    The HTTP status code generated by the origin server for this occurrence of the problem.
    """
    title: Literal["Unprocessable Content"] = "Unprocessable Content"
    """
    A short, human-readable summary of the problem type. It should not change from occurrence to occurrence of the problem, except for purposes of localization.
    """
    detail: Literal[
        "The request content is syntactically correct but cannot be processed."
    ] = "The request content is syntactically correct but cannot be processed."
    """
    A human-readable explanation specific to this occurrence of the problem.
    """


class InvalidBodyPropertyFormat(ProblemDetails):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: Literal[
        "https://eoap.github.io/problems-registry/invalid-body-property-format"
    ] = "https://eoap.github.io/problems-registry/invalid-body-property-format"
    """
    A URI reference that identifies the problem type.
    """
    status: Literal[400] = 400
    """
    The HTTP status code generated by the origin server for this occurrence of the problem.
    """
    title: Literal["Invalid Body Property Format"] = "Invalid Body Property Format"
    """
    A short, human-readable summary of the problem type. It should not change from occurrence to occurrence of the problem, except for purposes of localization.
    """
    detail: Literal["The request body contains a malformed property."] = (
        "The request body contains a malformed property."
    )
    """
    A human-readable explanation specific to this occurrence of the problem.
    """


class InvalidBodyPropertyValue(ProblemDetails):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: Literal[
        "https://eoap.github.io/problems-registry/invalid-body-property-value"
    ] = "https://eoap.github.io/problems-registry/invalid-body-property-value"
    """
    A URI reference that identifies the problem type.
    """
    status: Literal[400] = 400
    """
    The HTTP status code generated by the origin server for this occurrence of the problem.
    """
    title: Literal["Invalid Body Property Value"] = "Invalid Body Property Value"
    """
    A short, human-readable summary of the problem type. It should not change from occurrence to occurrence of the problem, except for purposes of localization.
    """
    detail: Literal["The request body contains an invalid body property value."] = (
        "The request body contains an invalid body property value."
    )
    """
    A human-readable explanation specific to this occurrence of the problem.
    """


class InvalidParameters(ProblemDetails):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: Literal["https://eoap.github.io/problems-registry/invalid-parameters"] = (
        "https://eoap.github.io/problems-registry/invalid-parameters"
    )
    """
    A URI reference that identifies the problem type.
    """
    status: Literal[400] = 400
    """
    The HTTP status code generated by the origin server for this occurrence of the problem.
    """
    title: Literal["Invalid parameters"] = "Invalid parameters"
    """
    A short, human-readable summary of the problem type. It should not change from occurrence to occurrence of the problem, except for purposes of localization.
    """
    detail: Literal[
        "The request contained invalid, or malformed parameters (path or header or query)."
    ] = "The request contained invalid, or malformed parameters (path or header or query)."
    """
    A human-readable explanation specific to this occurrence of the problem.
    """


class InvalidRequestHeaderFormat(ProblemDetails):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: Literal[
        "https://eoap.github.io/problems-registry/invalid-request-header-format"
    ] = "https://eoap.github.io/problems-registry/invalid-request-header-format"
    """
    A URI reference that identifies the problem type.
    """
    status: Literal[400] = 400
    """
    The HTTP status code generated by the origin server for this occurrence of the problem.
    """
    title: Literal["Invalid Request Header Format"] = "Invalid Request Header Format"
    """
    A short, human-readable summary of the problem type. It should not change from occurrence to occurrence of the problem, except for purposes of localization.
    """
    detail: Literal["The request contains a malformed request header parameter."] = (
        "The request contains a malformed request header parameter."
    )
    """
    A human-readable explanation specific to this occurrence of the problem.
    """


class InvalidRequestParameterFormat(ProblemDetails):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: Literal[
        "https://eoap.github.io/problems-registry/invalid-request-parameter-format"
    ] = "https://eoap.github.io/problems-registry/invalid-request-parameter-format"
    """
    A URI reference that identifies the problem type.
    """
    status: Literal[400] = 400
    """
    The HTTP status code generated by the origin server for this occurrence of the problem.
    """
    title: Literal["Invalid Request Parameter Format"] = (
        "Invalid Request Parameter Format"
    )
    """
    A short, human-readable summary of the problem type. It should not change from occurrence to occurrence of the problem, except for purposes of localization.
    """
    detail: Literal["The request contains a malformed request query parameter."] = (
        "The request contains a malformed request query parameter."
    )
    """
    A human-readable explanation specific to this occurrence of the problem.
    """


class InvalidRequestParameterValue(ProblemDetails):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: Literal[
        "https://eoap.github.io/problems-registry/invalid-request-parameter-value"
    ] = "https://eoap.github.io/problems-registry/invalid-request-parameter-value"
    """
    A URI reference that identifies the problem type.
    """
    status: Literal[400] = 400
    """
    The HTTP status code generated by the origin server for this occurrence of the problem.
    """
    title: Literal["Invalid Request Parameter Value"] = (
        "Invalid Request Parameter Value"
    )
    """
    A short, human-readable summary of the problem type. It should not change from occurrence to occurrence of the problem, except for purposes of localization.
    """
    detail: Literal["The request body contains an invalid request parameter value."] = (
        "The request body contains an invalid request parameter value."
    )
    """
    A human-readable explanation specific to this occurrence of the problem.
    """


class LicenseCancelled(ProblemDetails):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: Literal["https://eoap.github.io/problems-registry/license-cancelled"] = (
        "https://eoap.github.io/problems-registry/license-cancelled"
    )
    """
    A URI reference that identifies the problem type.
    """
    status: Literal[503] = 503
    """
    The HTTP status code generated by the origin server for this occurrence of the problem.
    """
    title: Literal["License Cancelled"] = "License Cancelled"
    """
    A short, human-readable summary of the problem type. It should not change from occurrence to occurrence of the problem, except for purposes of localization.
    """
    detail: Literal[
        "The service is unavailable as the license associated with your client or organization has been cancelled. Please contact your account manager or representative."
    ] = "The service is unavailable as the license associated with your client or organization has been cancelled. Please contact your account manager or representative."
    """
    A human-readable explanation specific to this occurrence of the problem.
    """


class LicenseExpired(ProblemDetails):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: Literal["https://eoap.github.io/problems-registry/license-expired"] = (
        "https://eoap.github.io/problems-registry/license-expired"
    )
    """
    A URI reference that identifies the problem type.
    """
    status: Literal[503] = 503
    """
    The HTTP status code generated by the origin server for this occurrence of the problem.
    """
    title: Literal["License Expired"] = "License Expired"
    """
    A short, human-readable summary of the problem type. It should not change from occurrence to occurrence of the problem, except for purposes of localization.
    """
    detail: Literal[
        "The service is unavailable as the license associated with your client or organization has expired. Please contact your account manager or representative."
    ] = "The service is unavailable as the license associated with your client or organization has expired. Please contact your account manager or representative."
    """
    A human-readable explanation specific to this occurrence of the problem.
    """


class MissingBodyProperty(ProblemDetails):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: Literal["https://eoap.github.io/problems-registry/missing-body-property"] = (
        "https://eoap.github.io/problems-registry/missing-body-property"
    )
    """
    A URI reference that identifies the problem type.
    """
    status: Literal[400] = 400
    """
    The HTTP status code generated by the origin server for this occurrence of the problem.
    """
    title: Literal["Missing body property"] = "Missing body property"
    """
    A short, human-readable summary of the problem type. It should not change from occurrence to occurrence of the problem, except for purposes of localization.
    """
    detail: Literal["The request is missing an expected body property."] = (
        "The request is missing an expected body property."
    )
    """
    A human-readable explanation specific to this occurrence of the problem.
    """


class MissingRequestHeader(ProblemDetails):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: Literal["https://eoap.github.io/problems-registry/missing-request-header"] = (
        "https://eoap.github.io/problems-registry/missing-request-header"
    )
    """
    A URI reference that identifies the problem type.
    """
    status: Literal[400] = 400
    """
    The HTTP status code generated by the origin server for this occurrence of the problem.
    """
    title: Literal["Missing request header"] = "Missing request header"
    """
    A short, human-readable summary of the problem type. It should not change from occurrence to occurrence of the problem, except for purposes of localization.
    """
    detail: Literal["The request is missing an expected HTTP request header."] = (
        "The request is missing an expected HTTP request header."
    )
    """
    A human-readable explanation specific to this occurrence of the problem.
    """


class MissingRequestParameter(ProblemDetails):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: Literal[
        "https://eoap.github.io/problems-registry/missing-request-parameter"
    ] = "https://eoap.github.io/problems-registry/missing-request-parameter"
    """
    A URI reference that identifies the problem type.
    """
    status: Literal[400] = 400
    """
    The HTTP status code generated by the origin server for this occurrence of the problem.
    """
    title: Literal["Missing request parameter"] = "Missing request parameter"
    """
    A short, human-readable summary of the problem type. It should not change from occurrence to occurrence of the problem, except for purposes of localization.
    """
    detail: Literal["The request is missing an expected query or path parameter."] = (
        "The request is missing an expected query or path parameter."
    )
    """
    A human-readable explanation specific to this occurrence of the problem.
    """


class NotFound(ProblemDetails):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: Literal["https://eoap.github.io/problems-registry/not-found"] = (
        "https://eoap.github.io/problems-registry/not-found"
    )
    """
    A URI reference that identifies the problem type.
    """
    status: Literal[404] = 404
    """
    The HTTP status code generated by the origin server for this occurrence of the problem.
    """
    title: Literal["Not Found"] = "Not Found"
    """
    A short, human-readable summary of the problem type. It should not change from occurrence to occurrence of the problem, except for purposes of localization.
    """
    detail: Literal["The requested resource was not found."] = (
        "The requested resource was not found."
    )
    """
    A human-readable explanation specific to this occurrence of the problem.
    """


class ServerError(ProblemDetails):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: Literal["https://eoap.github.io/problems-registry/server-error"] = (
        "https://eoap.github.io/problems-registry/server-error"
    )
    """
    A URI reference that identifies the problem type.
    """
    status: Literal[500] = 500
    """
    The HTTP status code generated by the origin server for this occurrence of the problem.
    """
    title: Literal["Server Error"] = "Server Error"
    """
    A short, human-readable summary of the problem type. It should not change from occurrence to occurrence of the problem, except for purposes of localization.
    """
    detail: Literal["The server encountered an unexpected error."] = (
        "The server encountered an unexpected error."
    )
    """
    A human-readable explanation specific to this occurrence of the problem.
    """


class ServiceUnavailable(ProblemDetails):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: Literal["https://eoap.github.io/problems-registry/service-unavailable"] = (
        "https://eoap.github.io/problems-registry/service-unavailable"
    )
    """
    A URI reference that identifies the problem type.
    """
    status: Literal[503] = 503
    """
    The HTTP status code generated by the origin server for this occurrence of the problem.
    """
    title: Literal["Service Unavailable"] = "Service Unavailable"
    """
    A short, human-readable summary of the problem type. It should not change from occurrence to occurrence of the problem, except for purposes of localization.
    """
    detail: Literal["The service is currently unavailable."] = (
        "The service is currently unavailable."
    )
    """
    A human-readable explanation specific to this occurrence of the problem.
    """


class Unauthorized(ProblemDetails):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: Literal["https://eoap.github.io/problems-registry/unauthorized"] = (
        "https://eoap.github.io/problems-registry/unauthorized"
    )
    """
    A URI reference that identifies the problem type.
    """
    status: Literal[401] = 401
    """
    The HTTP status code generated by the origin server for this occurrence of the problem.
    """
    title: Literal["Unauthorized"] = "Unauthorized"
    """
    A short, human-readable summary of the problem type. It should not change from occurrence to occurrence of the problem, except for purposes of localization.
    """
    detail: Literal[
        "Access token not set or invalid, and the requested resource could not be returned."
    ] = "Access token not set or invalid, and the requested resource could not be returned."
    """
    A human-readable explanation specific to this occurrence of the problem.
    """


class ValidationError(ProblemDetails):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: Literal["https://eoap.github.io/problems-registry/validation-error"] = (
        "https://eoap.github.io/problems-registry/validation-error"
    )
    """
    A URI reference that identifies the problem type.
    """
    status: Literal[422] = 422
    """
    The HTTP status code generated by the origin server for this occurrence of the problem.
    """
    title: Literal["Validation Error"] = "Validation Error"
    """
    A short, human-readable summary of the problem type. It should not change from occurrence to occurrence of the problem, except for purposes of localization.
    """
    detail: Literal["The request is not valid."] = "The request is not valid."
    """
    A human-readable explanation specific to this occurrence of the problem.
    """


class EoapProblemDetailsRegistry(
    RootModel[
        AlreadyExists
        | BadRequest
        | BusinessRuleViolation
        | Conflict
        | FailedDependency
        | Forbidden
        | Gone
        | InsufficientStorage
        | InvalidBodyPropertyFormat
        | InvalidBodyPropertyValue
        | InvalidParameters
        | InvalidRequestHeaderFormat
        | InvalidRequestParameterFormat
        | InvalidRequestParameterValue
        | LicenseCancelled
        | LicenseExpired
        | MissingBodyProperty
        | MissingRequestHeader
        | MissingRequestParameter
        | MethodNotAllowed
        | NotAcceptable
        | NotFound
        | NotImplemented
        | RequestTimeout
        | ServerError
        | ServiceUnavailable
        | Unauthorized
        | UnavailableForLegalReasons
        | UnprocessableContent
        | ValidationError
    ]
):
    root: Annotated[
        AlreadyExists
        | BadRequest
        | BusinessRuleViolation
        | Conflict
        | FailedDependency
        | Forbidden
        | Gone
        | InsufficientStorage
        | InvalidBodyPropertyFormat
        | InvalidBodyPropertyValue
        | InvalidParameters
        | InvalidRequestHeaderFormat
        | InvalidRequestParameterFormat
        | InvalidRequestParameterValue
        | LicenseCancelled
        | LicenseExpired
        | MissingBodyProperty
        | MissingRequestHeader
        | MissingRequestParameter
        | MethodNotAllowed
        | NotAcceptable
        | NotFound
        | NotImplemented
        | RequestTimeout
        | ServerError
        | ServiceUnavailable
        | Unauthorized
        | UnavailableForLegalReasons
        | UnprocessableContent
        | ValidationError,
        Field(title="EOAP Problem Details Registry"),
    ]
