# generated by datamodel-codegen:
#   filename:  schema.yaml
#   timestamp: 2026-06-30T15:29:44+00:00

from __future__ import annotations
from pydantic import BaseModel
from pydantic import ConfigDict, Field, RootModel
from typing import Literal


class ErrorDetail(BaseModel):
    """
    An object to provide explicit details on a problem towards an API consumer.
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    detail: str = Field(..., max_length=4096)
    """
    A granular description on the specific error related to a body property, query parameter, path parameters, and/or header.
    """
    pointer: str | None = Field(None, max_length=1024)
    """
    A JSON Pointer to a specific request body property that is the source of error.
    """
    parameter: str | None = Field(None, max_length=1024)
    """
    The name of the query or path parameter that is the source of error.
    """
    header: str | None = Field(None, max_length=1024)
    """
    The name of the header that is the source of error.
    """
    code: str | None = Field(None, max_length=50)
    """
    A string containing additional provider specific codes to identify the error context.
    """


class ProblemDetails(BaseModel):
    """
    The `ProblemDetails` object provides detailed information about an errors that occurred during an API call execution. This problem object conforms to the [RFC9457](https://www.rfc-editor.org/info/rfc9457) (formerly [RFC7807](https://tools.ietf.org/html/rfc7807)).
    The object is extended with the following properties: - `code` - a string identifier to aid the provider team better understand the error - `errors` - and array of errors providing contextual information on the root cause of the problem
    The `ProblemDetails` referenced by this domain utilize the [EOAP Problems Registry](https://eoap.github.io/problems-registry/).
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    instance: str | None = Field(None, max_length=1024)
    """
    A URI reference that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced.
    """
    code: str | None = Field(None, max_length=50)
    """
    An API specific error code aiding the provider team understand the error based on their own potential taxonomy or registry.
    """
    errors: list[ErrorDetail] | None = Field(None, max_length=1000)
    """
    An array of error details to accompany a problem details response.
    """


class AlreadyExists(ProblemDetails):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: Literal["https://eoap.github.io/problems-registry/already-exists"] = (
        "https://eoap.github.io/problems-registry/already-exists"
    )
    """
    A URI reference that identifies the problem type.
    """
    status: Literal[409] = 409
    """
    The HTTP status code generated by the origin server for this occurrence of the problem.
    """
    title: Literal["Already exists"] = "Already exists"
    """
    A short, human-readable summary of the problem type. It should not change from occurrence to occurrence of the problem, except for purposes of localization.
    """
    detail: Literal["The resource being created already exists."] = (
        "The resource being created already exists."
    )
    """
    A human-readable explanation specific to this occurrence of the problem.
    """


class BadRequest(ProblemDetails):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: Literal["https://eoap.github.io/problems-registry/bad-request"] = (
        "https://eoap.github.io/problems-registry/bad-request"
    )
    """
    A URI reference that identifies the problem type.
    """
    status: Literal[400] = 400
    """
    The HTTP status code generated by the origin server for this occurrence of the problem.
    """
    title: Literal["Bad Request"] = "Bad Request"
    """
    A short, human-readable summary of the problem type. It should not change from occurrence to occurrence of the problem, except for purposes of localization.
    """
    detail: Literal["The request is invalid or malformed."] = (
        "The request is invalid or malformed."
    )
    """
    A human-readable explanation specific to this occurrence of the problem.
    """


class BusinessRuleViolation(ProblemDetails):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: Literal[
        "https://eoap.github.io/problems-registry/business-rule-violation"
    ] = "https://eoap.github.io/problems-registry/business-rule-violation"
    """
    A URI reference that identifies the problem type.
    """
    status: Literal[422] = 422
    """
    The HTTP status code generated by the origin server for this occurrence of the problem.
    """
    title: Literal["Business Rule Violation"] = "Business Rule Violation"
    """
    A short, human-readable summary of the problem type. It should not change from occurrence to occurrence of the problem, except for purposes of localization.
    """
    detail: Literal["The request body is invalid and not meeting business rules."] = (
        "The request body is invalid and not meeting business rules."
    )
    """
    A human-readable explanation specific to this occurrence of the problem.
    """


class Forbidden(ProblemDetails):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: Literal["https://eoap.github.io/problems-registry/forbidden"] = (
        "https://eoap.github.io/problems-registry/forbidden"
    )
    """
    A URI reference that identifies the problem type.
    """
    status: Literal[403] = 403
    """
    The HTTP status code generated by the origin server for this occurrence of the problem.
    """
    title: Literal["Forbidden"] = "Forbidden"
    """
    A short, human-readable summary of the problem type. It should not change from occurrence to occurrence of the problem, except for purposes of localization.
    """
    detail: Literal[
        "The resource could not be returned as the requestor is not authorized."
    ] = "The resource could not be returned as the requestor is not authorized."
    """
    A human-readable explanation specific to this occurrence of the problem.
    """


class InvalidBodyPropertyFormat(ProblemDetails):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: Literal[
        "https://eoap.github.io/problems-registry/invalid-body-property-format"
    ] = "https://eoap.github.io/problems-registry/invalid-body-property-format"
    """
    A URI reference that identifies the problem type.
    """
    status: Literal[400] = 400
    """
    The HTTP status code generated by the origin server for this occurrence of the problem.
    """
    title: Literal["Invalid Body Property Format"] = "Invalid Body Property Format"
    """
    A short, human-readable summary of the problem type. It should not change from occurrence to occurrence of the problem, except for purposes of localization.
    """
    detail: Literal["The request body contains a malformed property."] = (
        "The request body contains a malformed property."
    )
    """
    A human-readable explanation specific to this occurrence of the problem.
    """


class InvalidBodyPropertyValue(ProblemDetails):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: Literal[
        "https://eoap.github.io/problems-registry/invalid-body-property-value"
    ] = "https://eoap.github.io/problems-registry/invalid-body-property-value"
    """
    A URI reference that identifies the problem type.
    """
    status: Literal[400] = 400
    """
    The HTTP status code generated by the origin server for this occurrence of the problem.
    """
    title: Literal["Invalid Body Property Value"] = "Invalid Body Property Value"
    """
    A short, human-readable summary of the problem type. It should not change from occurrence to occurrence of the problem, except for purposes of localization.
    """
    detail: Literal["The request body contains an invalid body property value."] = (
        "The request body contains an invalid body property value."
    )
    """
    A human-readable explanation specific to this occurrence of the problem.
    """


class InvalidParameters(ProblemDetails):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: Literal["https://eoap.github.io/problems-registry/invalid-parameters"] = (
        "https://eoap.github.io/problems-registry/invalid-parameters"
    )
    """
    A URI reference that identifies the problem type.
    """
    status: Literal[400] = 400
    """
    The HTTP status code generated by the origin server for this occurrence of the problem.
    """
    title: Literal["Invalid parameters"] = "Invalid parameters"
    """
    A short, human-readable summary of the problem type. It should not change from occurrence to occurrence of the problem, except for purposes of localization.
    """
    detail: Literal[
        "The request contained invalid, or malformed parameters (path or header or query)."
    ] = "The request contained invalid, or malformed parameters (path or header or query)."
    """
    A human-readable explanation specific to this occurrence of the problem.
    """


class InvalidRequestHeaderFormat(ProblemDetails):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: Literal[
        "https://eoap.github.io/problems-registry/invalid-request-header-format"
    ] = "https://eoap.github.io/problems-registry/invalid-request-header-format"
    """
    A URI reference that identifies the problem type.
    """
    status: Literal[400] = 400
    """
    The HTTP status code generated by the origin server for this occurrence of the problem.
    """
    title: Literal["Invalid Request Header Format"] = "Invalid Request Header Format"
    """
    A short, human-readable summary of the problem type. It should not change from occurrence to occurrence of the problem, except for purposes of localization.
    """
    detail: Literal["The request contains a malformed request header parameter."] = (
        "The request contains a malformed request header parameter."
    )
    """
    A human-readable explanation specific to this occurrence of the problem.
    """


class InvalidRequestParameterFormat(ProblemDetails):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: Literal[
        "https://eoap.github.io/problems-registry/invalid-request-parameter-format"
    ] = "https://eoap.github.io/problems-registry/invalid-request-parameter-format"
    """
    A URI reference that identifies the problem type.
    """
    status: Literal[400] = 400
    """
    The HTTP status code generated by the origin server for this occurrence of the problem.
    """
    title: Literal["Invalid Request Parameter Format"] = (
        "Invalid Request Parameter Format"
    )
    """
    A short, human-readable summary of the problem type. It should not change from occurrence to occurrence of the problem, except for purposes of localization.
    """
    detail: Literal["The request contains a malformed request query parameter."] = (
        "The request contains a malformed request query parameter."
    )
    """
    A human-readable explanation specific to this occurrence of the problem.
    """


class InvalidRequestParameterValue(ProblemDetails):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: Literal[
        "https://eoap.github.io/problems-registry/invalid-request-parameter-value"
    ] = "https://eoap.github.io/problems-registry/invalid-request-parameter-value"
    """
    A URI reference that identifies the problem type.
    """
    status: Literal[400] = 400
    """
    The HTTP status code generated by the origin server for this occurrence of the problem.
    """
    title: Literal["Invalid Request Parameter Value"] = (
        "Invalid Request Parameter Value"
    )
    """
    A short, human-readable summary of the problem type. It should not change from occurrence to occurrence of the problem, except for purposes of localization.
    """
    detail: Literal["The request body contains an invalid request parameter value."] = (
        "The request body contains an invalid request parameter value."
    )
    """
    A human-readable explanation specific to this occurrence of the problem.
    """


class LicenseCancelled(ProblemDetails):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: Literal["https://eoap.github.io/problems-registry/license-cancelled"] = (
        "https://eoap.github.io/problems-registry/license-cancelled"
    )
    """
    A URI reference that identifies the problem type.
    """
    status: Literal[503] = 503
    """
    The HTTP status code generated by the origin server for this occurrence of the problem.
    """
    title: Literal["License Cancelled"] = "License Cancelled"
    """
    A short, human-readable summary of the problem type. It should not change from occurrence to occurrence of the problem, except for purposes of localization.
    """
    detail: Literal[
        "The service is unavailable as the license associated with your client or organization has been cancelled. Please contact your account manager or representative."
    ] = "The service is unavailable as the license associated with your client or organization has been cancelled. Please contact your account manager or representative."
    """
    A human-readable explanation specific to this occurrence of the problem.
    """


class LicenseExpired(ProblemDetails):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: Literal["https://eoap.github.io/problems-registry/license-expired"] = (
        "https://eoap.github.io/problems-registry/license-expired"
    )
    """
    A URI reference that identifies the problem type.
    """
    status: Literal[503] = 503
    """
    The HTTP status code generated by the origin server for this occurrence of the problem.
    """
    title: Literal["License Expired"] = "License Expired"
    """
    A short, human-readable summary of the problem type. It should not change from occurrence to occurrence of the problem, except for purposes of localization.
    """
    detail: Literal[
        "The service is unavailable as the license associated with your client or organization has expired. Please contact your account manager or representative."
    ] = "The service is unavailable as the license associated with your client or organization has expired. Please contact your account manager or representative."
    """
    A human-readable explanation specific to this occurrence of the problem.
    """


class MissingBodyProperty(ProblemDetails):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: Literal["https://eoap.github.io/problems-registry/missing-body-property"] = (
        "https://eoap.github.io/problems-registry/missing-body-property"
    )
    """
    A URI reference that identifies the problem type.
    """
    status: Literal[400] = 400
    """
    The HTTP status code generated by the origin server for this occurrence of the problem.
    """
    title: Literal["Missing body property"] = "Missing body property"
    """
    A short, human-readable summary of the problem type. It should not change from occurrence to occurrence of the problem, except for purposes of localization.
    """
    detail: Literal["The request is missing an expected body property."] = (
        "The request is missing an expected body property."
    )
    """
    A human-readable explanation specific to this occurrence of the problem.
    """


class MissingRequestHeader(ProblemDetails):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: Literal["https://eoap.github.io/problems-registry/missing-request-header"] = (
        "https://eoap.github.io/problems-registry/missing-request-header"
    )
    """
    A URI reference that identifies the problem type.
    """
    status: Literal[400] = 400
    """
    The HTTP status code generated by the origin server for this occurrence of the problem.
    """
    title: Literal["Missing request header"] = "Missing request header"
    """
    A short, human-readable summary of the problem type. It should not change from occurrence to occurrence of the problem, except for purposes of localization.
    """
    detail: Literal["The request is missing an expected HTTP request header."] = (
        "The request is missing an expected HTTP request header."
    )
    """
    A human-readable explanation specific to this occurrence of the problem.
    """


class MissingRequestParameter(ProblemDetails):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: Literal[
        "https://eoap.github.io/problems-registry/missing-request-parameter"
    ] = "https://eoap.github.io/problems-registry/missing-request-parameter"
    """
    A URI reference that identifies the problem type.
    """
    status: Literal[400] = 400
    """
    The HTTP status code generated by the origin server for this occurrence of the problem.
    """
    title: Literal["Missing request parameter"] = "Missing request parameter"
    """
    A short, human-readable summary of the problem type. It should not change from occurrence to occurrence of the problem, except for purposes of localization.
    """
    detail: Literal["The request is missing an expected query or path parameter."] = (
        "The request is missing an expected query or path parameter."
    )
    """
    A human-readable explanation specific to this occurrence of the problem.
    """


class NotFound(ProblemDetails):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: Literal["https://eoap.github.io/problems-registry/not-found"] = (
        "https://eoap.github.io/problems-registry/not-found"
    )
    """
    A URI reference that identifies the problem type.
    """
    status: Literal[404] = 404
    """
    The HTTP status code generated by the origin server for this occurrence of the problem.
    """
    title: Literal["Not Found"] = "Not Found"
    """
    A short, human-readable summary of the problem type. It should not change from occurrence to occurrence of the problem, except for purposes of localization.
    """
    detail: Literal["The requested resource was not found."] = (
        "The requested resource was not found."
    )
    """
    A human-readable explanation specific to this occurrence of the problem.
    """


class ServerError(ProblemDetails):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: Literal["https://eoap.github.io/problems-registry/server-error"] = (
        "https://eoap.github.io/problems-registry/server-error"
    )
    """
    A URI reference that identifies the problem type.
    """
    status: Literal[500] = 500
    """
    The HTTP status code generated by the origin server for this occurrence of the problem.
    """
    title: Literal["Server Error"] = "Server Error"
    """
    A short, human-readable summary of the problem type. It should not change from occurrence to occurrence of the problem, except for purposes of localization.
    """
    detail: Literal["The server encountered an unexpected error."] = (
        "The server encountered an unexpected error."
    )
    """
    A human-readable explanation specific to this occurrence of the problem.
    """


class ServiceUnavailable(ProblemDetails):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: Literal["https://eoap.github.io/problems-registry/service-unavailable"] = (
        "https://eoap.github.io/problems-registry/service-unavailable"
    )
    """
    A URI reference that identifies the problem type.
    """
    status: Literal[503] = 503
    """
    The HTTP status code generated by the origin server for this occurrence of the problem.
    """
    title: Literal["Service Unavailable"] = "Service Unavailable"
    """
    A short, human-readable summary of the problem type. It should not change from occurrence to occurrence of the problem, except for purposes of localization.
    """
    detail: Literal["The service is currently unavailable."] = (
        "The service is currently unavailable."
    )
    """
    A human-readable explanation specific to this occurrence of the problem.
    """


class Unauthorized(ProblemDetails):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: Literal["https://eoap.github.io/problems-registry/unauthorized"] = (
        "https://eoap.github.io/problems-registry/unauthorized"
    )
    """
    A URI reference that identifies the problem type.
    """
    status: Literal[401] = 401
    """
    The HTTP status code generated by the origin server for this occurrence of the problem.
    """
    title: Literal["Unauthorized"] = "Unauthorized"
    """
    A short, human-readable summary of the problem type. It should not change from occurrence to occurrence of the problem, except for purposes of localization.
    """
    detail: Literal[
        "Access token not set or invalid, and the requested resource could not be returned."
    ] = "Access token not set or invalid, and the requested resource could not be returned."
    """
    A human-readable explanation specific to this occurrence of the problem.
    """


class ValidationError(ProblemDetails):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: Literal["https://eoap.github.io/problems-registry/validation-error"] = (
        "https://eoap.github.io/problems-registry/validation-error"
    )
    """
    A URI reference that identifies the problem type.
    """
    status: Literal[422] = 422
    """
    The HTTP status code generated by the origin server for this occurrence of the problem.
    """
    title: Literal["Validation Error"] = "Validation Error"
    """
    A short, human-readable summary of the problem type. It should not change from occurrence to occurrence of the problem, except for purposes of localization.
    """
    detail: Literal["The request is not valid."] = "The request is not valid."
    """
    A human-readable explanation specific to this occurrence of the problem.
    """


class EoapProblemDetailsRegistry(
    RootModel[
        AlreadyExists
        | BadRequest
        | BusinessRuleViolation
        | Forbidden
        | InvalidBodyPropertyFormat
        | InvalidBodyPropertyValue
        | InvalidParameters
        | InvalidRequestHeaderFormat
        | InvalidRequestParameterFormat
        | InvalidRequestParameterValue
        | LicenseCancelled
        | LicenseExpired
        | MissingBodyProperty
        | MissingRequestHeader
        | MissingRequestParameter
        | NotFound
        | ServerError
        | ServiceUnavailable
        | Unauthorized
        | ValidationError
    ]
):
    root: (
        AlreadyExists
        | BadRequest
        | BusinessRuleViolation
        | Forbidden
        | InvalidBodyPropertyFormat
        | InvalidBodyPropertyValue
        | InvalidParameters
        | InvalidRequestHeaderFormat
        | InvalidRequestParameterFormat
        | InvalidRequestParameterValue
        | LicenseCancelled
        | LicenseExpired
        | MissingBodyProperty
        | MissingRequestHeader
        | MissingRequestParameter
        | NotFound
        | ServerError
        | ServiceUnavailable
        | Unauthorized
        | ValidationError
    ) = Field(..., title="EOAP Problem Details Registry")
