# Copyright 2026 EOAP
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

site_name: Problems Registry
site_url: https://eoap.github.io/problems-registry/
site_author: Fabrice Brito, Simone Tripodi
repo_url: https://github.com/eoap/problems-registry/
repo_name: eoap/problems-registry

theme:
  logo: imgs/icon-eoap.png
  name: readthedocs

  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode

plugins:
- search
- mermaid2:
    version: 11.4.1

markdown_extensions:
- pymdownx.details
- abbr
- admonition
- footnotes
- pymdownx.caret
- pymdownx.mark
- pymdownx.tilde
- pymdownx.arithmatex:
    generic: true
- pymdownx.superfences
- pymdownx.tabbed
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_div_format
- attr_list
- pymdownx.snippets:
    base_path: './'
- pymdownx.highlight:
    line_spans: __span

extra_css:
- styles/css/app.css
  
extra_javascript:
- javascripts/config.js
- https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
- Home: index.md
- Problems Registry:
  - EOAP Problem Types:
    - already-exists.md
    - business-rule-violation.md
    - invalid-body-property-format.md
    - invalid-body-property-value.md
    - invalid-request-header-format.md
    - invalid-request-parameter-format.md
    - invalid-request-parameter-value.md
    - invalid-state-transition.md
    - license-cancelled.md
    - license-expired.md
    - missing-body-property.md
    - missing-request-header.md
    - missing-request-parameter.md
    - validation-error.md
  - Common Problem Types:
    - bad-request.md
    - forbidden.md
    - invalid-parameters.md
    - not-found.md
    - service-unavailable.md
    - server-error.md
    - unauthorized.md
- Schemas:
  - JSON Schema: json-schema.md
  - OpenAPI: openapi.yaml

copyright: <a href="https://www.apache.org/licenses/LICENSE-2.0"><img src="https://img.shields.io/badge/license-Apache%20License%202.0-blue"" alt="Apache License, Version 2.0" /></a>
